### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by DarkNeedle** [nemanjam/nemanjam.github.io#8]
Just wanted to point out a minor bug. The colors shift once you initially land on the website (default is dark mode), switch to light mode, then back to dark mode. The colors remain shifted. It looks great by the way but it's a bug.

**Comment by nemanjam** [comment]
Can you make a video capture and post it here? 

Does same happen on this demo website?

https://astro-paper.pages.dev/posts/

**Comment by DarkNeedle** [comment]
https://github.com/user-attachments/assets/84998885-ee3a-447e-904a-d31f8a255e86

**Comment by DarkNeedle** [comment]
I tested it in the code (local run) and on your primary website. The same behavior is exhibited.

**Comment by nemanjam** [comment]
I see, good catch. I assumed something else from the original post, now I understand. This happens only for links color. I will have a look.

**Comment by nemanjam** [comment]
I found it, primary color was undefined for default dark theme. I it is a consequence of the fact that I have just set up system for dark modes and color themes and defined few colors to confirm it's working, but never really defined proper color palettes for color themes. I should do it soon I think. Thank you for catching this undefined color.

```css
--th-primary: var(--var-color-blue-300);
```

Can you clear your browser cache `Ctrl + F5` and confirm its working now? Website is redeployed.

https://nemanjamitic.com/

**Comment by DarkNeedle** [comment]
I cleared my cache in both Safari and Chrome. I still see the same behavior being exhibited.

**Comment by nemanjam** [comment]
You can inspect link and check that this `--var-color-blue-300` variable is defined.

![image](https://github.com/user-attachments/assets/43ef71c8-5b1c-40da-8e1e-a7a199e89ff8)

**Comment by DarkNeedle** [comment]
The commit is in the footer of your site. Not sure why I am seeing the same behavior across Chrome and Safari. I will try a different device. Happens the same on a mobile device running Safari and Chrome.

**Comment by DarkNeedle** [comment]
Are you seeing that there is no longer an issues per the video?

**Comment by nemanjam** [comment]
I can see its fine, its light blue that is almost gray.

[Screencast from 08.09.2024. 11:29:04.webm](https://github.com/user-attachments/assets/caf15a7f-52ab-4e63-a1d2-090b2b5fdb31)

**Comment by DarkNeedle** [comment]
Yes I do see the colors are fine for dark and for light, however, if you have a look at the video again, when the page transitions from dark to light, the color is good. when it transitions back and forth from dark to light, light to dark the color does not stick, it alternates between green and light blue.

Example
0. Go to blog page
1. Initial dark mode, light blue
2. toggle to light mode, green
3. toggle to dark mode, green
4. toggle to light mode, light blue
5. repeat this over and over and the colors alternate with both dark and light mode being equally light blue and green

**Comment by nemanjam** [comment]
Default themes (both light and dark) have blue primary color, green themes have green primary color.

![image](https://github.com/user-attachments/assets/4d26b19b-c872-465e-9a30-44af7fb7f2e6)

![image](https://github.com/user-attachments/assets/1545ccfa-e022-4d97-a718-df4a7be2fd7e)

**Comment by DarkNeedle** [comment]
Ah ok, so it seems set to alternate every time the mode is toggled with each press. This then is the coded behavior?

**Comment by nemanjam** [comment]
Yes, you can add more themes with semantic colors of choice and border radius.

**Comment by DarkNeedle** [comment]
Thank you for the clarification, very much appreciated

**Comment by DarkNeedle** [comment]
thanks again
